function [fitresult, gof] = createFits1(ambs, probs, rsqprd)
%CREATEFITS1(AMBS,PROBS,RSQPRD)
%  Create fits.
%
%  Data for 'untitled fit 1' fit:
%      X Input : ambs
%      Y Input : probs
%      Z Output: rsqprd
%  Data for 'untitled fit 2' fit:
%      X Input : ambs
%      Y Input : probs
%      Z Output: rsqprd
%  Data for 'untitled fit 3' fit:
%      X Input : ambs
%      Y Input : probs
%      Z Output: rsqprd
%  Data for 'untitled fit 4' fit:
%      X Input : ambs
%      Y Input : probs
%      Z Output: rsqprd
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Mar-2015 15:00:50

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 4, 1 );
gof = struct( 'sse', cell( 4, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( ambs, probs, rsqprd );

% Set up fittype and options.
ft = fittype( 'poly55' );

% Fit model to data.
[fitresult{1}, gof(1)] = fit( [xData, yData], zData, ft );

% Make contour plot.
figure( 'Name', 'untitled fit 1' );
subplot(2,2,1);
h = plot( fitresult{1}, [xData, yData], zData,'MarkerSize',2, 'Style', 'Contour');
legend( h, 'untitled fit 1', 'rsqprd vs. ambs, probs', 'Location', 'NorthEast' );
% Label axes
xlabel ambs
ylabel probs
grid on

%% Fit: 'untitled fit 2'.
[xData, yData, zData] = prepareSurfaceData( ambs, probs, rsqprd );

% Set up fittype and options.
ft = fittype( 'poly55' );

% Fit model to data.
[fitresult{2}, gof(2)] = fit( [xData, yData], zData, ft );

% Plot fit with data.
%figure( 'Name', 'untitled fit 2' );
subplot(2,2,2);
h = plot( fitresult{2}, [xData, yData], zData,'MarkerSize',2 );
legend( h, 'untitled fit 2', 'rsqprd vs. ambs, probs', 'Location', 'NorthEast' );
% Label axes
xlabel ambs
ylabel probs
zlabel rsqprd
grid on
view( -74.5, 34.0 );

%% Fit: 'untitled fit 3'.
[xData, yData, zData] = prepareSurfaceData( ambs, probs, rsqprd );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult{3}, gof(3)] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
%figure( 'Name', 'untitled fit 3' );
subplot(2,2,4);
h = plot( fitresult{3}, [xData, yData], zData,'MarkerSize',2 );
legend( h, 'untitled fit 3', 'rsqprd vs. ambs, probs', 'Location', 'NorthEast' );
% Label axes
xlabel ambs
ylabel probs
zlabel rsqprd
grid on
view( -58.5, 40.0 );

%% Fit: 'untitled fit 4'.
[xData, yData, zData] = prepareSurfaceData( ambs, probs, rsqprd );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult{4}, gof(4)] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Make contour plot.
%figure( 'Name', 'untitled fit 4' );
subplot(2,2,3);
h = plot( fitresult{4}, [xData, yData], zData, 'Style', 'Contour','MarkerSize',2 );
legend( h, 'untitled fit 4', 'rsqprd vs. ambs, probs', 'Location', 'NorthEast' );
% Label axes
xlabel ambs
ylabel probs
grid on


